### ISSUE TITLE
Getting error when creating market

### ISSUE THREAD

**Issue by Gsuz** [sayantank/serum-explorer#22]
<img width="1227" alt="Screenshot 2022-11-21 at 20 32 06" src="https://user-images.githubusercontent.com/310239/203152899-91264838-6753-4f0a-b885-ecfcacea98e5.png">

**Comment by Gsuz** [comment]
got this from the browser console -> 

> [explorer]:  Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 5: custom program error: 0x1000675
    at to.sendEncodedTransaction (_app-8133355bade436c9.js:1:113708)
    at async to.sendRawTransaction (_app-8133355bade436c9.js:1:113243)

**Comment by ZuluSpl0it** [comment]
I'm also getting the same error while trying to create a market. I was able to do so on the devnet, but not on the mainnet.

**Comment by MistaBitniq** [comment]
same here

**Comment by WolfSolana** [comment]
i am having issues in creating market ID and i need someone to guide me in step by step on how is done and secondly ill like to confirm if this address is already created for i have triad many times.
3LxaYzsRMPxgjh5qYjuPZoTzENaztXoRVJqkKJtoAzzo

**Comment by Black4Sky** [comment]
Has anyone been able to solve the problem with Failed to create market transaction? Who can help with this error?
<img width="735" alt="Failed" src="https://github.com/sayantank/serum-explorer/assets/136338919/44253973-93f9-4f6a-9d06-2b39399d6f15">
